-- https://school.programmers.co.kr/learn/courses/30/lessons/133026
SELECT ICECREAM_INFO.INGREDIENT_TYPE, SUM(FIRST_HALF.TOTAL_ORDER) as TOTAL_ORDER
FROM FIRST_HALF, ICECREAM_INFO
WHERE ICECREAM_INFO.FLAVOR = FIRST_HALF.FLAVOR
GROUP BY ICECREAM_INFO.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER;