-- https://school.programmers.co.kr/learn/courses/30/lessons/157339
SELECT c.CAR_ID, c.CAR_TYPE, FLOOR(c.DAILY_FEE*30 * (1 - p.DISCOUNT_RATE/100)) as FEE
FROM CAR_RENTAL_COMPANY_CAR c
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h ON c.CAR_ID = h.CAR_ID AND ('2022-11-01' BETWEEN h.START_DATE AND h.END_DATE OR '2022-11-30' BETWEEN h.START_DATE AND h.END_DATE)
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p ON c.CAR_TYPE = p.CAR_TYPE AND p.DURATION_TYPE = '30일 이상'
WHERE c.CAR_TYPE IN ('세단', 'SUV') AND h.CAR_ID IS NULL AND FLOOR(c.DAILY_FEE*30 * (1 - p.DISCOUNT_RATE/100)) BETWEEN 500000 and 1999999
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;